import { Booking, Car, Customer, Review } from './types';

export const cars: Car[] = [
  {
    id: '1',
    name: 'Tesla Model 3',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2024,
    pricePerDay: 89,
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
    seats: 5,
    fuelType: 'Electric',
    transmission: 'Automatic',
    category: 'Luxury',
    features: ['Autopilot', 'Premium Sound', 'Glass Roof', 'Heated Seats'],
    available: true,
    rating: 4.9,
    reviews: 128,
  },
  {
    id: '2',
    name: 'BMW X5',
    brand: 'BMW',
    model: 'X5',
    year: 2024,
    pricePerDay: 120,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
    seats: 7,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    category: 'SUV',
    features: ['Panoramic Roof', 'Leather Seats', 'Navigation', 'Parking Assist'],
    available: true,
    rating: 4.8,
    reviews: 96,
  },
  {
    id: '3',
    name: 'Mercedes C-Class',
    brand: 'Mercedes',
    model: 'C-Class',
    year: 2024,
    pricePerDay: 95,
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
    seats: 5,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    category: 'Luxury',
    features: ['MBUX System', 'Ambient Lighting', 'Wireless Charging', 'Burmester Sound'],
    available: true,
    rating: 4.7,
    reviews: 84,
  },
  {
    id: '4',
    name: 'Toyota Camry',
    brand: 'Toyota',
    model: 'Camry',
    year: 2024,
    pricePerDay: 55,
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
    seats: 5,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    category: 'Compact',
    features: ['Apple CarPlay', 'Safety Sense', 'Adaptive Cruise', 'Lane Assist'],
    available: true,
    rating: 4.6,
    reviews: 156,
  },
  {
    id: '5',
    name: 'Porsche 911',
    brand: 'Porsche',
    model: '911',
    year: 2024,
    pricePerDay: 250,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    seats: 2,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    category: 'Sports',
    features: ['Sport Chrono', 'PASM', 'Bose Sound', 'Sport Exhaust'],
    available: true,
    rating: 5.0,
    reviews: 42,
  },
  {
    id: '6',
    name: 'Honda Civic',
    brand: 'Honda',
    model: 'Civic',
    year: 2024,
    pricePerDay: 45,
    image: 'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800&q=80',
    seats: 5,
    fuelType: 'Petrol',
    transmission: 'Manual',
    category: 'Economy',
    features: ['Honda Sensing', 'Apple CarPlay', 'Android Auto', 'Sunroof'],
    available: true,
    rating: 4.5,
    reviews: 210,
  },
  {
    id: '7',
    name: 'Audi Q7',
    brand: 'Audi',
    model: 'Q7',
    year: 2024,
    pricePerDay: 135,
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    seats: 7,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    category: 'SUV',
    features: ['Virtual Cockpit', 'Air Suspension', 'Matrix LED', 'B&O Sound'],
    available: false,
    rating: 4.8,
    reviews: 67,
  },
  {
    id: '8',
    name: 'Ford Mustang',
    brand: 'Ford',
    model: 'Mustang GT',
    year: 2024,
    pricePerDay: 150,
    image: 'https://images.unsplash.com/photo-1584345604476-8ec5f82d718c?w=800&q=80',
    seats: 4,
    fuelType: 'Petrol',
    transmission: 'Manual',
    category: 'Sports',
    features: ['V8 Engine', 'Track Apps', 'Recaro Seats', 'MagneRide'],
    available: true,
    rating: 4.9,
    reviews: 89,
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    customerName: 'Nida Javed',
    customerImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    rating: 5,
    comment: 'Amazing experience! The Tesla was spotless and the booking process was incredibly smooth. Will definitely rent again.',
    date: '2024-01-15',
    carName: 'Tesla Model 3',
  },
  {
    id: '2',
    customerName: 'Amr Rizkallah',
    customerImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    rating: 5,
    comment: 'Best car rental service I have ever used. The BMW X5 was perfect for our family trip. Highly recommended!',
    date: '2024-01-12',
    carName: 'BMW X5',
  },
  {
    id: '3',
    customerName: 'Thi Phuong Nguyen',
    customerImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    rating: 4,
    comment: 'Great selection of cars and competitive prices. The pickup was quick and hassle-free.',
    date: '2024-01-10',
    carName: 'Mercedes C-Class',
  },
];

export const bookings: Booking[] = [
  {
    id: 'BK001',
    carId: '1',
    customerName: 'John Smith',
    customerEmail: 'john@example.com',
    customerPhone: '+1 234 567 8900',
    pickupDate: '2024-02-01',
    returnDate: '2024-02-05',
    pickupLocation: 'LAX Airport',
    totalPrice: 356,
    status: 'confirmed',
    extras: ['GPS', 'Child Seat'],
    paymentStatus: 'paid',
    createdAt: '2024-01-20',
  },
  {
    id: 'BK002',
    carId: '2',
    customerName: 'Sarah Johnson',
    customerEmail: 'sarah@example.com',
    customerPhone: '+1 234 567 8901',
    pickupDate: '2024-02-03',
    returnDate: '2024-02-07',
    pickupLocation: 'Downtown LA',
    totalPrice: 480,
    status: 'pending',
    extras: ['Insurance Plus'],
    paymentStatus: 'pending',
    createdAt: '2024-01-21',
  },
  {
    id: 'BK003',
    carId: '5',
    customerName: 'Michael Chen',
    customerEmail: 'michael@example.com',
    customerPhone: '+1 234 567 8902',
    pickupDate: '2024-01-28',
    returnDate: '2024-01-30',
    pickupLocation: 'Beverly Hills',
    totalPrice: 500,
    status: 'active',
    extras: [],
    paymentStatus: 'paid',
    createdAt: '2024-01-15',
  },
];

export const customers: Customer[] = [
  {
    id: 'C001',
    name: 'John Smith',
    email: 'john@example.com',
    phone: '+1 234 567 8900',
    totalBookings: 5,
    totalSpent: 1580,
    joinedAt: '2023-06-15',
  },
  {
    id: 'C002',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '+1 234 567 8901',
    totalBookings: 3,
    totalSpent: 890,
    joinedAt: '2023-08-20',
  },
  {
    id: 'C003',
    name: 'Michael Chen',
    email: 'michael@example.com',
    phone: '+1 234 567 8902',
    totalBookings: 8,
    totalSpent: 3200,
    joinedAt: '2023-03-10',
  },
];

export const locations = ['LAX Airport', 'Downtown LA', 'Santa Monica', 'Beverly Hills', 'Hollywood', 'Long Beach', 'Pasadena', 'Burbank Airport'];
